version: "3.7"
services: 
    youtube-downloader-api-prod:
        build:  
          context: ./
          dockerfile: ./Dockerfile.prod
        ports:
          - "4000:4000"
        restart: always
        container_name: youtube-downloader-api-prod       
        volumes: 
            - .:/app
            - /app/node_modules