version: "3.7"
services: 
    youtube-downloader-api-dev:
        container_name: youtube-downloader-api-dev
        build:
          context: ./
          dockerfile: ./Dockerfile
        volumes: 
            - .:/app
            - /app/node_modules